---
- hosts: mysql
  strategy: linear
  become: true
  roles:
  - { role: mysql, become: yes }
  vars_files:
    - vars/default.yml

  handlers:
    - name: Restart mysql
      service:
        name: mysql
        state: restarted  

- hosts: wordpress
  strategy: linear
  become: true
  roles:
  - { role: openlitespeed, become: yes }
  - { role: php, become: yes }
  - { role: wordpress, become: yes }
  vars_files:
    - vars/default.yml

 